Feature: Customer login
  Generated by manual (authoring)

  Scenario: Happy path
    Given User opens the login page.
    Given User enters a valid email and password combination.
    Given click on login button to log user incorrect.

# specId: 2add92dde2ee5d37a17c5c487aa4f9744cb9b04f3ab95aaf6682521ac9e3de0a
# graphId: 2d1b8cd5-1bd1-4b9a-8a6b-6dcfb678ff6c
# generatedAt: 2025-11-12T07:25:39.815Z
