Feature: Customer login
  Generated by stagehand (authoring)

  Scenario: Happy path
    Given User opens the login page.
    Given User enters a valid email and password combination.
    Given Submit button logs user in.

# specId: 3b2dab459499ec182dd4e397cfda79f56e4b5444bbfe74111790c71bc0dbd5a8
# graphId: 50cb168b-cdb5-4c0d-a824-9bca0ea578dd
# generatedAt: 2025-11-10T07:35:31.342Z
