Feature: Customer login
  Generated by manual (authoring)

  Scenario: Happy path
    Given User opens the login page.
    Given User enters a valid email and password combination.
    Given Submit button logs user in.

# specId: 3b2dab459499ec182dd4e397cfda79f56e4b5444bbfe74111790c71bc0dbd5a8
# graphId: 3cb892a1-2d33-403f-814b-4c83aaa09d90
# generatedAt: 2025-11-12T06:04:39.560Z
