Feature: Customer login
  Generated by manual (authoring)

  Scenario: Happy path
    When User nagivate to login page.
    When User enters a valid email and password combination.
    When click on login button to log user incorrect.

# specId: 6df3a1b0be9cd838f50e6dae7445c46ffef03968acfa325c1b694c7b2a05c49d
# graphId: 7e664c0a-f2bd-4e8a-86f1-97434bb1f86b
# generatedAt: 2025-11-12T07:48:24.183Z
