Feature: Customer login
  Generated by manual (authoring)

  Scenario: Authenticate With Valid Credentials
    Given I am on the login page
    When I enter email as <E2E_USER_EMAIL>
    And I enter password as <E2E_USER_PASSWORD>
    And I click the submit button
    Then I should see text Welcome back

# specId: b9aa49ee-bcc2-4af6-be87-50f4d1c0d585
# graphId: 4e426729-ecde-4fa2-a73f-70094748f338
# generatedAt: 2025-11-09T09:28:19.574Z
